# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Enplug add-on
version: "1.2.0"
slug: enplug
description: Enplug add-on
url: "https://github.com/philsoph/homeassistant-addons/tree/main/enplug"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/philsoph/{arch}-homeassistant-addons"
